In [2]:
import struct
import pandas as pd
import os

# Define the DATA_MOUSE structure format
data_mouse_format = "iiiII"

# Event code to event name mapping
event_mapping = {
    512: "MouseEvent(WM_MOUSEMOVE)",
    513: "Click()",
    514: "MouseEvent(WM_LBUTTONUP)",
    515: "DblClick()",
    516: "RightClick()",
    517: "MouseEvent(WM_RBUTTONUP)",
    518: "RightDblClick()",
    519: "MiddleClick()",
    520: "MouseEvent(WM_MBUTTONUP)",
    521: "MiddleDlbClick()",
}

# Open the .ef file for reading in binary mode
data_list = []
with open("7.ef", "rb") as file:
    while True:
        data = file.read(struct.calcsize(data_mouse_format))
        if not data:
            break
        x, y, ncode, TimeStamp, ProcessNo = struct.unpack(data_mouse_format, data)

        # Translate the event code to event name
        event_name = event_mapping.get(ncode, "Unknown")

        data_list.append({
            "x": x,
            "y": y,
            "ncode": ncode,
            "event": event_name,
            "TimeStamp": TimeStamp,
            "ProcessNo": ProcessNo
        })

# Create a Pandas DataFrame
df = pd.DataFrame(data_list)

# You now have a DataFrame (df) containing the processed data

data_list = []
with open("3.ef", "rb") as file:
    while True:
        data = file.read(struct.calcsize(data_mouse_format))
        if not data:
            break
        x, y, ncode, TimeStamp, ProcessNo = struct.unpack(data_mouse_format, data)

        # Translate the event code to event name
        event_name = event_mapping.get(ncode, "Unknown")

        data_list.append({
            "x": x,
            "y": y,
            "ncode": ncode,
            "event": event_name,
            "TimeStamp": TimeStamp,
            "ProcessNo": ProcessNo
        })

# Create a Pandas DataFrame
df3 = pd.DataFrame(data_list)
df3.to_csv("df3")
# You now have a DataFrame (df) containing the processed data

FileNotFoundError: [Errno 2] No such file or directory: '7.ef'

In [15]:
import struct
import pandas as pd
import os

# Define the DATA_MOUSE structure format
data_mouse_format = "iiiII"

# Event code to event name mapping
event_mapping = {
    512: "MouseEvent(WM_MOUSEMOVE)",
    513: "Click()",
    514: "MouseEvent(WM_LBUTTONUP)",
    515: "DblClick()",
    516: "RightClick()",
    517: "MouseEvent(WM_RBUTTONUP)",
    518: "RightDblClick()",
    519: "MiddleClick()",
    520: "MouseEvent(WM_MBUTTONUP)",
    521: "MiddleDlbClick()",
}

def read_ef_file(file_name):
    data_list = []
    with open(file_name, "rb") as file:
        while True:
            data = file.read(struct.calcsize(data_mouse_format))
            if not data:
                break
            x, y, ncode, TimeStamp, ProcessNo = struct.unpack(data_mouse_format, data)

            # Translate the event code to event name
            event_name = event_mapping.get(ncode, "Unknown")

            data_list.append({
                "x": x,
                "y": y,
                "ncode": ncode,
                "event": event_name,
                "TimeStamp": TimeStamp,
                "ProcessNo": ProcessNo
            })

    # Create a Pandas DataFrame
    df = pd.DataFrame(data_list)
    return df

# File names you want to process

In [16]:
def read_tail_head(df):
    first_record = df.head(1)
    last_record = df.tail(1)
    substraction  = last_record['TimeStamp'].iloc[0] - first_record['TimeStamp'].iloc[0]
    print(f"First {first_record['TimeStamp'].iloc[0]}, last {last_record['TimeStamp'].iloc[0]} Substraction {substraction}")

In [19]:
file_names = ["19.ef","20.ef", "21.ef", "22.ef","23.ef", "24.ef", '25.ef', "26.ef", "27.ef"]

# Process each file and store DataFrames in a dictionary
dfs = {}
for i, file_name in enumerate(file_names):
    df_i = read_ef_file(file_name)
    dfs[file_name] = df_i
    read_tail_head(dfs[file_name])
    df_i.to_csv(f'{i}.csv')
    print(" Shape of DataFrame:", df_i.shape)
# Now you have DataFrames df_2, df_4, and df_7 for each file

First 80031, last 12055454 Substraction 11975423
 Shape of DataFrame: (310801, 6)
First 67654, last 3849289 Substraction 3781635
 Shape of DataFrame: (75552, 6)
First 51422, last 1332445 Substraction 1281023
 Shape of DataFrame: (7451, 6)
First 108911, last 469453 Substraction 360542
 Shape of DataFrame: (7928, 6)
First 53340, last 75538 Substraction 22198
 Shape of DataFrame: (409, 6)
First 496295, last 633236 Substraction 136941
 Shape of DataFrame: (9393, 6)
First 96953, last 165357 Substraction 68404
 Shape of DataFrame: (3743, 6)
First 57907, last 168906 Substraction 110999
 Shape of DataFrame: (5766, 6)
First 69117, last 252734 Substraction 183617
 Shape of DataFrame: (7578, 6)

In [124]:

first_record = df.head(1)
last_record = df.tail(1)
substraction  = last_record['TimeStamp'].iloc[0] - first_record['TimeStamp'].iloc[0]

print(f"First {first_record['TimeStamp'].iloc[0]}, last {last_record['TimeStamp'].iloc[0]} Substraction {substraction}")
first_record = df3.head(1)
last_record = df3.tail(1)
substraction  = last_record['TimeStamp'].iloc[0] - first_record['TimeStamp'].iloc[0]

print(f"First {first_record['TimeStamp'].iloc[0]}, last {last_record['TimeStamp'].iloc[0]} Substraction {substraction}")

First 69849, last 3458819 Substraction 3388970
First 2889111, last 134920461 Substraction 132031350
First 22525, last 10365910 Substraction 10343385

In [97]:
df.head()

     x    y  ncode                     event  TimeStamp  ProcessNo
0  640  512    512  MouseEvent(WM_MOUSEMOVE)      48089          0
1  640  512    512  MouseEvent(WM_MOUSEMOVE)      48159          0
2  640  512    512  MouseEvent(WM_MOUSEMOVE)      48208          0
3  640  512    512  MouseEvent(WM_MOUSEMOVE)      48241          0
4  640  512    512  MouseEvent(WM_MOUSEMOVE)      48242          0

In [98]:
df.tail()

         x    y  ncode    event  TimeStamp  ProcessNo
48051  667  381    160  Unknown    2078270          3
48052  677  395    160  Unknown    2078280          3
48053  685  404    160  Unknown    2078289          3
48054  694  421    160  Unknown    2078299          3
48055  697  430    160  Unknown    2078309          3

In [102]:
import datetime

# Windows FILETIME timestamp examples
timestamp_0_minutes = 48089
timestamp_30_minutes = 2078309

# Convert FILETIME to datetime
epoch = datetime.datetime(1601, 1, 1)
timestamp_0_minutes_dt = epoch + datetime.timedelta(microseconds=timestamp_0_minutes * 10)
timestamp_30_minutes_dt = epoch + datetime.timedelta(microseconds=timestamp_30_minutes * 10)

# Print the converted timestamps
print("0 Minute Timestamp:", timestamp_0_minutes_dt)
print("30 Minute Timestamp:", timestamp_30_minutes_dt)

0 Minute Timestamp: 1601-01-01 00:00:00.480890
30 Minute Timestamp: 1601-01-01 00:00:20.783090

In [103]:
windows_timestamp = 48089  # Replace with the actual timestamp value
microseconds = windows_timestamp / 10
windows_epoch = datetime.datetime(1601, 1, 1)
converted_time = windows_epoch + datetime.timedelta(microseconds=microseconds)
print(converted_time)

1601-01-01 00:00:00.004809

2078309 - 48089

In [104]:
import os

In [105]:
base_path = 'shen-continuous\\data'
dirs  = os.listdir(base_path)

In [106]:
for dir in dirs:
    conc_path = os.path.join(base_path, dir)
    print(conc_path)
    print(os.listdir(conc_path))

shen-continuous\data\1
['1_1.ef', '1_2.ef', '1_3.ef', '1_4.ef', '1_5.ef', '1_6.ef', '1_7.ef', '1_8.ef', '1_9.ef', '2_1.ef', '2_2.ef', '2_3.ef', '3_1.ef', '3_2.ef', '3_3.ef', '3_4.ef', '4_1.ef', '4_2.ef', '4_3.ef', '4_4.ef']
shen-continuous\data\10
['10_1.ef', '10_2.ef', '1_1.ef', '1_2.ef', '1_3.ef', '1_4.ef', '1_5.ef', '34_1.ef', '34_2.ef', '34_3.ef', '35_1.ef', '35_2.ef', '36_1.ef', '40_1.ef', '40_2.ef', '49_1.ef', '49_2.ef', '49_3.ef', '57_1.ef', '57_2.ef', '57_3.ef', '57_4.ef', '57_5.ef', '57_6.ef', '63_1.ef', '63_2.ef', '63_3.ef', '63_4.ef', '68_1.ef', '68_2.ef', '68_3.ef', '68_4.ef', '68_5.ef', '68_6.ef', '68_7.ef', '68_8.ef', '8_1.ef', '8_2.ef', '9_1.ef', '9_2.ef', '9_3.ef']
shen-continuous\data\11
['1.ef', '10.ef', '11.ef', '12.ef', '13.ef', '14.ef', '15.ef', '16.ef', '17.ef', '18.ef', '19.ef', '2.ef', '20.ef', '21.ef', '22.ef', '3.ef', '4.ef', '5.ef', '6.ef', '7.ef', '8.ef', '9.ef']
shen-continuous\data\12
['1.ef', '10.ef', '11.ef', '12.ef', '13.ef', '14.ef', '15.ef', '16.ef', '17.ef', '18.ef', '19.ef', '2.ef', '20.ef', '21.ef', '22.ef', '23.ef', '24.ef', '25.ef', '3.ef', '4.ef', '5.ef', '6.ef', '7.ef', '8.ef', '9.ef']
shen-continuous\data\13
['1.ef', '10.ef', '11.ef', '12.ef', '13.ef', '14.ef', '15.ef', '16.ef', '17.ef', '18.ef', '19.ef', '2.ef', '20.ef', '21.ef', '22.ef', '23.ef', '24.ef', '25.ef', '26.ef', '27.ef', '28.ef', '29.ef', '3.ef', '30.ef', '4.ef', '5.ef', '6.ef', '7.ef', '8.ef', '9.ef']
shen-continuous\data\14
['1.ef', '10.ef', '11.ef', '12.ef', '13.ef', '14.ef', '15.ef', '16.ef', '2.ef', '3.ef', '4.ef', '5.ef', '6.ef', '7.ef', '8.ef', '9.ef']
shen-continuous\data\15
['1.ef', '10.ef', '11.ef', '12.ef', '2.ef', '3.ef', '4.ef', '5.ef', '6.ef', '7.ef', '8.ef', '9.ef']
shen-continuous\data\16
['1.ef', '10.ef', '11.ef', '12.ef', '13.ef', '14.ef', '15.ef', '16.ef', '17.ef', '18.ef', '19.ef', '2.ef', '20.ef', '21.ef', '22.ef', '23.ef', '24.ef', '3.ef', '4.ef', '5.ef', '6.ef', '7.ef', '8.ef', '9.ef']
shen-continuous\data\17
['1_1.ef', '1_2.ef', '1_3.ef', '1_4.ef', '2_1.ef', '2_2.ef', '2_3.ef', '2_4.ef', '2_5.ef', '2_6.ef', '2_7.ef', '2_8.ef', '3_1.ef', '3_2.ef', '3_3.ef', '3_4.ef', '3_5.ef', '3_6.ef', '3_7.ef', '3_8.ef', '3_9.ef']
shen-continuous\data\18
['1.ef', '2.ef', '3.ef', '4.ef', '5.ef', '6.ef', '7.ef']
shen-continuous\data\19
['1.ef', '10.ef', '2.ef', '3.ef', '4.ef', '5.ef', '6.ef', '7.ef', '8.ef', '9.ef']
shen-continuous\data\2
['1_1.ef', '1_10.ef', '1_11.ef', '1_12.ef', '1_13.ef', '1_14.ef', '1_15.ef', '1_16.ef', '1_17.ef', '1_18.ef', '1_19.ef', '1_2.ef', '1_20.ef', '1_21.ef', '1_22.ef', '1_23.ef', '1_24.ef', '1_25.ef', '1_26.ef', '1_27.ef', '1_28.ef', '1_3.ef', '1_4.ef', '1_5.ef', '1_6.ef', '1_7.ef', '1_8.ef', '1_9.ef', '2_1.ef', '2_10.ef', '2_11.ef', '2_12.ef', '2_13.ef', '2_14.ef', '2_15.ef', '2_16.ef', '2_17.ef', '2_2.ef', '2_3.ef', '2_4.ef', '2_5.ef', '2_6.ef', '2_7.ef', '2_8.ef', '2_9.ef', '3_1.ef', '3_10.ef', '3_11.ef', '3_12.ef', '3_13.ef', '3_14.ef', '3_15.ef', '3_16.ef', '3_17.ef', '3_18.ef', '3_19.ef', '3_2.ef', '3_20.ef', '3_21.ef', '3_22.ef', '3_23.ef', '3_3.ef', '3_4.ef', '3_5.ef', '3_6.ef', '3_7.ef', '3_8.ef', '3_9.ef', '4_1.ef']
shen-continuous\data\20
['1.ef', '10.ef', '11.ef', '12.ef', '13.ef', '14.ef', '15.ef', '16.ef', '17.ef', '18.ef', '2.ef', '3.ef', '4.ef', '5.ef', '6.ef', '7.ef', '8.ef', '9.ef']
shen-continuous\data\21
['1.ef', '10.ef', '11.ef', '12.ef', '2.ef', '3.ef', '4.ef', '5.ef', '6.ef', '7.ef', '8.ef', '9.ef']
shen-continuous\data\22
['19.ef', '20.ef', '21.ef', '22.ef', '23.ef', '24.ef', '25.ef', '26.ef', '27.ef', '28.ef', '29.ef', '30.ef', '31.ef', '32.ef', '33.ef', '34.ef', '35.ef', '36.ef', '37.ef', '38.ef', '39.ef']
shen-continuous\data\23
['2_1.ef', '2_2.ef', '2_3.ef', '2_4.ef', '2_5.ef', '2_6.ef', '39_1.ef', '39_2.ef', '39_3.ef', '39_4.ef', '7_1.ef', '7_2.ef', '7_3.ef', '7_4.ef', '7_5.ef', '8_1.ef', '8_10.ef', '8_11.ef', '8_2.ef', '8_3.ef', '8_4.ef', '8_5.ef', '8_6.ef', '8_7.ef', '8_8.ef', '8_9.ef']
shen-continuous\data\24
['1.ef', '2.ef', '3.ef', '3_1.ef', '4_1.ef', '4_2.ef', '4_3.ef', '5.ef', '5_1.ef', '6_1.ef', '6_2.ef', '6_3.ef', '6_4.ef', '7.ef', '7_1.ef']
shen-continuous\data\25
['1_1.ef', '1_10.ef', '1_2.ef', '1_3.ef', '1_4.ef', '1_5.ef', '1_6.ef', '1_7.ef', '1_8.ef', '1_9.ef', '2_1.ef']
shen-continuous\data\26
['1_1.ef', '1_2.ef', '2_1.ef', '2_10.ef', '2_11.ef', '2_12.ef', '2_13.ef', '2_2.ef', '2_3.ef', '2_4.ef', '2_5.ef', '2_6.ef', '2_7.ef', '2_8.ef', '2_9.ef']
shen-continuous\data\27
['6_1.ef', '6_10.ef', '6_11.ef', '6_2.ef', '6_3.ef', '6_4.ef', '6_5.ef', '6_6.ef', '6_7.ef', '6_8.ef', '6_9.ef', '7_1.ef', '7_2.ef', '7_3.ef', '8_1.ef', '8_2.ef', '8_3.ef', '8_4.ef', '8_5.ef', '8_6.ef', '9_1.ef', '9_2.ef', '9_3.ef', '9_4.ef', '9_5.ef', '9_6.ef', '9_7.ef', '9_8.ef', '9_9.ef']
shen-continuous\data\28
['10.ef', '11.ef', '12.ef', '18.ef', '2.ef', '21.ef', '29.ef', '3.ef', '33.ef', '36.ef', '37.ef', '38.ef', '4.ef', '42.ef', '43.ef', '7.ef', '9.ef']
shen-continuous\data\3
['1_1.ef', '1_10.ef', '1_11.ef', '1_12.ef', '1_13.ef', '1_14.ef', '1_15.ef', '1_16.ef', '1_2.ef', '1_3.ef', '1_4.ef', '1_5.ef', '1_6.ef', '1_7.ef', '1_8.ef', '1_9.ef', '2_1.ef', '2_10.ef', '2_11.ef', '2_12.ef', '2_13.ef', '2_14.ef', '2_15.ef', '2_16.ef', '2_17.ef', '2_18.ef', '2_19.ef', '2_2.ef', '2_20.ef', '2_21.ef', '2_3.ef', '2_4.ef', '2_5.ef', '2_6.ef', '2_7.ef', '2_8.ef', '2_9.ef']
shen-continuous\data\4
['1_1.ef', '1_10.ef', '1_11.ef', '1_2.ef', '1_3.ef', '1_4.ef', '1_5.ef', '1_6.ef', '1_7.ef', '1_8.ef', '1_9.ef', '2_1.ef', '3_1.ef', '3_2.ef', '3_3.ef', '3_4.ef', '3_5.ef', '3_6.ef', '3_7.ef', '3_8.ef', '4_1.ef', '4_2.ef', '4_3.ef', '4_4.ef', '5_1.ef', '5_2.ef', '5_3.ef', '6_1.ef', '7_1.ef', '7_2.ef']
shen-continuous\data\5
['11_1.ef', '39_1.ef', '39_2.ef', '46.ef', '47_1.ef', '47_2.ef', '47_3.ef', '47_4.ef', '48_1.ef', '48_2.ef', '49.ef', '51_1.ef', '51_2.ef', '52_1.ef', '52_2.ef', '52_3.ef', '52_4.ef', '54_1.ef', '54_2.ef', '54_3.ef', '55.ef', '56.ef', '57.ef']
shen-continuous\data\6
['4_1.ef', '4_10.ef', '4_2.ef', '4_3.ef', '4_4.ef', '4_5.ef', '4_6.ef', '4_7.ef', '4_8.ef', '4_9.ef', '5_1.ef', '5_10.ef', '5_11.ef', '5_12.ef', '5_2.ef', '5_3.ef', '5_4.ef', '5_5.ef', '5_6.ef', '5_7.ef', '5_8.ef', '5_9.ef']
shen-continuous\data\7
['1_1.ef', '1_2.ef', '1_3.ef', '1_4.ef', '2_1.ef', '2_2.ef', '2_3.ef', '2_4.ef', '2_5.ef', '2_6.ef', '2_7.ef', '2_8.ef', '2_9.ef', '3_1.ef', '3_2.ef', '3_3.ef', '3_4.ef', '3_5.ef', '3_6.ef', '3_7.ef', '4_1.ef', '4_2.ef', '5_1.ef', '5_10.ef', '5_11.ef', '5_12.ef', '5_13.ef', '5_14.ef', '5_15.ef', '5_16.ef', '5_17.ef', '5_18.ef', '5_19.ef', '5_2.ef', '5_3.ef', '5_4.ef', '5_5.ef', '5_6.ef', '5_7.ef', '5_8.ef', '5_9.ef', '6_1.ef', '6_10.ef', '6_11.ef', '6_2.ef', '6_3.ef', '6_4.ef', '6_5.ef', '6_6.ef', '6_7.ef', '6_8.ef', '6_9.ef']
shen-continuous\data\8
['10_1.ef', '10_2.ef', '10_3.ef', '10_4.ef', '10_5.ef', '10_6.ef', '10_7.ef', '22_1.ef', '22_2.ef', '22_3.ef', '22_4.ef', '22_5.ef', '22_6.ef', '22_7.ef', '9_1.ef', '9_2.ef', '9_3.ef', '9_4.ef', '9_5.ef', '9_6.ef']
shen-continuous\data\9
['14_1.ef', '14_2.ef', '14_3.ef', '14_4.ef', '14_5.ef', '15_1.ef', '15_2.ef', '22_1.ef', '22_2.ef', '24_1.ef', '24_2.ef', '39_1.ef', '39_2.ef', '39_3.ef', '39_4.ef', '3_1.ef', '4_1.ef', '4_2.ef', '4_3.ef', '4_4.ef', '53_1.ef', '53_2.ef', '53_3.ef', '53_4.ef', '53_5.ef', '5_1.ef', '5_2.ef', '6_1.ef']

In [107]:
df['event']

0        MouseEvent(WM_MOUSEMOVE)
1        MouseEvent(WM_MOUSEMOVE)
2        MouseEvent(WM_MOUSEMOVE)
3        MouseEvent(WM_MOUSEMOVE)
4        MouseEvent(WM_MOUSEMOVE)
                   ...
48051                     Unknown
48052                     Unknown
48053                     Unknown
48054                     Unknown
48055                     Unknown
Name: event, Length: 48056, dtype: object

In [108]:
event_counts = df["event"].value_counts()
print(event_counts)

MouseEvent(WM_MOUSEMOVE)    44089
Unknown                      3147
MouseEvent(WM_LBUTTONUP)      413
Click()                       394
DblClick()                     11
RightClick()                    1
MouseEvent(WM_RBUTTONUP)        1
Name: event, dtype: int64

In [109]:
df.to_csv('my_data.csv', index=False)  # Set index to False to exclude the index column

In [110]:
import datetime

timestamp = 233449388
dt_object = datetime.datetime.utcfromtimestamp(timestamp)
print(dt_object)

timestamp = 233449395
dt_object = datetime.datetime.utcfromtimestamp(timestamp)
print(dt_object)

1977-05-25 23:03:08
1977-05-25 23:03:15

In [111]:
import struct
import pandas as pd
import os

# Define the DATA_MOUSE structure format
data_mouse_format = "iiIII"

# Event code to event name mapping
event_mapping = {
    512: "MouseEvent(WM_MOUSEMOVE)",
    513: "Click()",
    514: "MouseEvent(WM_LBUTTONUP)",
    515: "DblClick()",
    516: "RightClick()",
    517: "MouseEvent(WM_RBUTTONUP)",
    518: "RightDblClick()",
    519: "MiddleClick()",
    520: "MouseEvent(WM_MBUTTONUP)",
    521: "MiddleDlbClick()",
}

# Folder containing .ef files
base_path = 'shen-continuous\\data'
data_folder = os.listdir(base_path)   # Replace with the correct path to your folders
basic_save_path = "ChaoShenCSV\\"
# Initialize a dictionary to store data for each prefix
data_dict = {}

# Iterate through the .ef files in the folder
for dir in data_folder:
    combined_path = os.path.join(base_path, dir)
    save_path = os.path.join(basic_save_path, dir)
    # Check if the directory already exists; if not, create it
    if not os.path.exists(save_path):
        os.makedirs(save_path)

    for ef_file in os.listdir(combined_path):
        if ef_file.endswith('.ef'):
            ef_file_path = os.path.join(combined_path, ef_file)
            print(ef_file)
            with open(ef_file_path, "rb") as file:
                data_list = []
                while True:
                    data = file.read(struct.calcsize(data_mouse_format))
                    if not data:
                        break
                    x, y, ncode, TimeStamp, ProcessNo = struct.unpack(data_mouse_format, data)

                    # Translate the event code to event name
                    event_name = event_mapping.get(ncode, "Unknown")

                    data_list.append({
                        "x": x,
                        "y": y,
                        "ncode": ncode,
                        "event": event_name,
                        "TimeStamp": TimeStamp,
                        "ProcessNo": ProcessNo
                    })

            # Determine the prefix (e.g., '1_', '2_') from the file name
            prefix = ef_file.split('_')[0]
            if prefix == ef_file:
                prefix = ef_file.split('.')[0]

            if prefix not in data_dict:
                data_dict[prefix] = []

            data_dict[prefix].extend(data_list)

# Create Pandas DataFrames and save to separate CSV files
    for prefix, data_list in data_dict.items():
        df = pd.DataFrame(data_list)
        csv_filename = os.path.join(save_path,f'combined_data_{prefix}.csv')
        df.to_csv(csv_filename, index=False)
        print(f"Combined data for {prefix} files saved to '{csv_filename}'")
    data_dict = {}

1_1.ef

1_2.ef
1_3.ef
1_4.ef
1_5.ef
1_6.ef
1_7.ef
1_8.ef
1_9.ef
2_1.ef
2_2.ef
2_3.ef
3_1.ef
3_2.ef
3_3.ef
3_4.ef
4_1.ef
4_2.ef
4_3.ef
4_4.ef
Combined data for 1 files saved to 'ChaoShenCSV\1\combined_data_1.csv'
Combined data for 2 files saved to 'ChaoShenCSV\1\combined_data_2.csv'
Combined data for 3 files saved to 'ChaoShenCSV\1\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\1\combined_data_4.csv'
10_1.ef
10_2.ef
1_1.ef
1_2.ef
1_3.ef
1_4.ef
1_5.ef
34_1.ef
34_2.ef
34_3.ef
35_1.ef
35_2.ef
36_1.ef
40_1.ef
40_2.ef
49_1.ef
49_2.ef
49_3.ef
57_1.ef
57_2.ef
57_3.ef
57_4.ef
57_5.ef
57_6.ef
63_1.ef
63_2.ef
63_3.ef
63_4.ef
68_1.ef
68_2.ef
68_3.ef
68_4.ef
68_5.ef
68_6.ef
68_7.ef
68_8.ef
8_1.ef
8_2.ef
9_1.ef
9_2.ef
9_3.ef
Combined data for 10 files saved to 'ChaoShenCSV\10\combined_data_10.csv'
Combined data for 1 files saved to 'ChaoShenCSV\10\combined_data_1.csv'
Combined data for 34 files saved to 'ChaoShenCSV\10\combined_data_34.csv'
Combined data for 35 files saved to 'ChaoShenCSV\10\combined_data_35.csv'
Combined data for 36 files saved to 'ChaoShenCSV\10\combined_data_36.csv'
Combined data for 40 files saved to 'ChaoShenCSV\10\combined_data_40.csv'
Combined data for 49 files saved to 'ChaoShenCSV\10\combined_data_49.csv'
Combined data for 57 files saved to 'ChaoShenCSV\10\combined_data_57.csv'
Combined data for 63 files saved to 'ChaoShenCSV\10\combined_data_63.csv'
Combined data for 68 files saved to 'ChaoShenCSV\10\combined_data_68.csv'
Combined data for 8 files saved to 'ChaoShenCSV\10\combined_data_8.csv'
Combined data for 9 files saved to 'ChaoShenCSV\10\combined_data_9.csv'
1.ef
10.ef
11.ef
12.ef
13.ef
14.ef
15.ef
16.ef
17.ef
18.ef
19.ef
2.ef
20.ef
21.ef
22.ef
3.ef
4.ef
5.ef
6.ef
7.ef
8.ef
9.ef
Combined data for 1 files saved to 'ChaoShenCSV\11\combined_data_1.csv'
Combined data for 10 files saved to 'ChaoShenCSV\11\combined_data_10.csv'
Combined data for 11 files saved to 'ChaoShenCSV\11\combined_data_11.csv'
Combined data for 12 files saved to 'ChaoShenCSV\11\combined_data_12.csv'
Combined data for 13 files saved to 'ChaoShenCSV\11\combined_data_13.csv'
Combined data for 14 files saved to 'ChaoShenCSV\11\combined_data_14.csv'
Combined data for 15 files saved to 'ChaoShenCSV\11\combined_data_15.csv'
Combined data for 16 files saved to 'ChaoShenCSV\11\combined_data_16.csv'
Combined data for 17 files saved to 'ChaoShenCSV\11\combined_data_17.csv'
Combined data for 18 files saved to 'ChaoShenCSV\11\combined_data_18.csv'
Combined data for 19 files saved to 'ChaoShenCSV\11\combined_data_19.csv'
Combined data for 2 files saved to 'ChaoShenCSV\11\combined_data_2.csv'
Combined data for 20 files saved to 'ChaoShenCSV\11\combined_data_20.csv'
Combined data for 21 files saved to 'ChaoShenCSV\11\combined_data_21.csv'
Combined data for 22 files saved to 'ChaoShenCSV\11\combined_data_22.csv'
Combined data for 3 files saved to 'ChaoShenCSV\11\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\11\combined_data_4.csv'
Combined data for 5 files saved to 'ChaoShenCSV\11\combined_data_5.csv'
Combined data for 6 files saved to 'ChaoShenCSV\11\combined_data_6.csv'
Combined data for 7 files saved to 'ChaoShenCSV\11\combined_data_7.csv'
Combined data for 8 files saved to 'ChaoShenCSV\11\combined_data_8.csv'
Combined data for 9 files saved to 'ChaoShenCSV\11\combined_data_9.csv'
1.ef
10.ef
11.ef
12.ef
13.ef
14.ef
15.ef
16.ef
17.ef
18.ef
19.ef
2.ef
20.ef
21.ef
22.ef
23.ef
24.ef
25.ef
3.ef
4.ef
5.ef
6.ef
7.ef
8.ef
9.ef
Combined data for 1 files saved to 'ChaoShenCSV\12\combined_data_1.csv'
Combined data for 10 files saved to 'ChaoShenCSV\12\combined_data_10.csv'
Combined data for 11 files saved to 'ChaoShenCSV\12\combined_data_11.csv'
Combined data for 12 files saved to 'ChaoShenCSV\12\combined_data_12.csv'
Combined data for 13 files saved to 'ChaoShenCSV\12\combined_data_13.csv'
Combined data for 14 files saved to 'ChaoShenCSV\12\combined_data_14.csv'
Combined data for 15 files saved to 'ChaoShenCSV\12\combined_data_15.csv'
Combined data for 16 files saved to 'ChaoShenCSV\12\combined_data_16.csv'
Combined data for 17 files saved to 'ChaoShenCSV\12\combined_data_17.csv'
Combined data for 18 files saved to 'ChaoShenCSV\12\combined_data_18.csv'
Combined data for 19 files saved to 'ChaoShenCSV\12\combined_data_19.csv'
Combined data for 2 files saved to 'ChaoShenCSV\12\combined_data_2.csv'
Combined data for 20 files saved to 'ChaoShenCSV\12\combined_data_20.csv'
Combined data for 21 files saved to 'ChaoShenCSV\12\combined_data_21.csv'
Combined data for 22 files saved to 'ChaoShenCSV\12\combined_data_22.csv'
Combined data for 23 files saved to 'ChaoShenCSV\12\combined_data_23.csv'
Combined data for 24 files saved to 'ChaoShenCSV\12\combined_data_24.csv'
Combined data for 25 files saved to 'ChaoShenCSV\12\combined_data_25.csv'
Combined data for 3 files saved to 'ChaoShenCSV\12\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\12\combined_data_4.csv'
Combined data for 5 files saved to 'ChaoShenCSV\12\combined_data_5.csv'
Combined data for 6 files saved to 'ChaoShenCSV\12\combined_data_6.csv'
Combined data for 7 files saved to 'ChaoShenCSV\12\combined_data_7.csv'
Combined data for 8 files saved to 'ChaoShenCSV\12\combined_data_8.csv'
Combined data for 9 files saved to 'ChaoShenCSV\12\combined_data_9.csv'
1.ef
10.ef
11.ef
12.ef
13.ef
14.ef
15.ef
16.ef
17.ef
18.ef
19.ef
2.ef
20.ef
21.ef
22.ef
23.ef
24.ef
25.ef
26.ef
27.ef
28.ef
29.ef
3.ef
30.ef
4.ef
5.ef
6.ef
7.ef
8.ef
9.ef
Combined data for 1 files saved to 'ChaoShenCSV\13\combined_data_1.csv'
Combined data for 10 files saved to 'ChaoShenCSV\13\combined_data_10.csv'
Combined data for 11 files saved to 'ChaoShenCSV\13\combined_data_11.csv'
Combined data for 12 files saved to 'ChaoShenCSV\13\combined_data_12.csv'
Combined data for 13 files saved to 'ChaoShenCSV\13\combined_data_13.csv'
Combined data for 14 files saved to 'ChaoShenCSV\13\combined_data_14.csv'
Combined data for 15 files saved to 'ChaoShenCSV\13\combined_data_15.csv'
Combined data for 16 files saved to 'ChaoShenCSV\13\combined_data_16.csv'
Combined data for 17 files saved to 'ChaoShenCSV\13\combined_data_17.csv'
Combined data for 18 files saved to 'ChaoShenCSV\13\combined_data_18.csv'
Combined data for 19 files saved to 'ChaoShenCSV\13\combined_data_19.csv'
Combined data for 2 files saved to 'ChaoShenCSV\13\combined_data_2.csv'
Combined data for 20 files saved to 'ChaoShenCSV\13\combined_data_20.csv'
Combined data for 21 files saved to 'ChaoShenCSV\13\combined_data_21.csv'
Combined data for 22 files saved to 'ChaoShenCSV\13\combined_data_22.csv'
Combined data for 23 files saved to 'ChaoShenCSV\13\combined_data_23.csv'
Combined data for 24 files saved to 'ChaoShenCSV\13\combined_data_24.csv'
Combined data for 25 files saved to 'ChaoShenCSV\13\combined_data_25.csv'
Combined data for 26 files saved to 'ChaoShenCSV\13\combined_data_26.csv'
Combined data for 27 files saved to 'ChaoShenCSV\13\combined_data_27.csv'
Combined data for 28 files saved to 'ChaoShenCSV\13\combined_data_28.csv'
Combined data for 29 files saved to 'ChaoShenCSV\13\combined_data_29.csv'
Combined data for 3 files saved to 'ChaoShenCSV\13\combined_data_3.csv'
Combined data for 30 files saved to 'ChaoShenCSV\13\combined_data_30.csv'
Combined data for 4 files saved to 'ChaoShenCSV\13\combined_data_4.csv'
Combined data for 5 files saved to 'ChaoShenCSV\13\combined_data_5.csv'
Combined data for 6 files saved to 'ChaoShenCSV\13\combined_data_6.csv'
Combined data for 7 files saved to 'ChaoShenCSV\13\combined_data_7.csv'
Combined data for 8 files saved to 'ChaoShenCSV\13\combined_data_8.csv'
Combined data for 9 files saved to 'ChaoShenCSV\13\combined_data_9.csv'
1.ef
10.ef
11.ef
12.ef
13.ef
14.ef
15.ef
16.ef
2.ef
3.ef
4.ef
5.ef
6.ef
7.ef
8.ef
9.ef
Combined data for 1 files saved to 'ChaoShenCSV\14\combined_data_1.csv'
Combined data for 10 files saved to 'ChaoShenCSV\14\combined_data_10.csv'
Combined data for 11 files saved to 'ChaoShenCSV\14\combined_data_11.csv'
Combined data for 12 files saved to 'ChaoShenCSV\14\combined_data_12.csv'
Combined data for 13 files saved to 'ChaoShenCSV\14\combined_data_13.csv'
Combined data for 14 files saved to 'ChaoShenCSV\14\combined_data_14.csv'
Combined data for 15 files saved to 'ChaoShenCSV\14\combined_data_15.csv'
Combined data for 16 files saved to 'ChaoShenCSV\14\combined_data_16.csv'
Combined data for 2 files saved to 'ChaoShenCSV\14\combined_data_2.csv'
Combined data for 3 files saved to 'ChaoShenCSV\14\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\14\combined_data_4.csv'
Combined data for 5 files saved to 'ChaoShenCSV\14\combined_data_5.csv'
Combined data for 6 files saved to 'ChaoShenCSV\14\combined_data_6.csv'
Combined data for 7 files saved to 'ChaoShenCSV\14\combined_data_7.csv'
Combined data for 8 files saved to 'ChaoShenCSV\14\combined_data_8.csv'
Combined data for 9 files saved to 'ChaoShenCSV\14\combined_data_9.csv'
1.ef
10.ef
11.ef
12.ef
2.ef
3.ef
4.ef
5.ef
6.ef
7.ef
8.ef
9.ef
Combined data for 1 files saved to 'ChaoShenCSV\15\combined_data_1.csv'
Combined data for 10 files saved to 'ChaoShenCSV\15\combined_data_10.csv'
Combined data for 11 files saved to 'ChaoShenCSV\15\combined_data_11.csv'
Combined data for 12 files saved to 'ChaoShenCSV\15\combined_data_12.csv'
Combined data for 2 files saved to 'ChaoShenCSV\15\combined_data_2.csv'
Combined data for 3 files saved to 'ChaoShenCSV\15\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\15\combined_data_4.csv'
Combined data for 5 files saved to 'ChaoShenCSV\15\combined_data_5.csv'
Combined data for 6 files saved to 'ChaoShenCSV\15\combined_data_6.csv'
Combined data for 7 files saved to 'ChaoShenCSV\15\combined_data_7.csv'
Combined data for 8 files saved to 'ChaoShenCSV\15\combined_data_8.csv'
Combined data for 9 files saved to 'ChaoShenCSV\15\combined_data_9.csv'
1.ef
10.ef
11.ef
12.ef
13.ef
14.ef
15.ef
16.ef
17.ef
18.ef
19.ef
2.ef
20.ef
21.ef
22.ef
23.ef
24.ef
3.ef
4.ef
5.ef
6.ef
7.ef
8.ef
9.ef
Combined data for 1 files saved to 'ChaoShenCSV\16\combined_data_1.csv'
Combined data for 10 files saved to 'ChaoShenCSV\16\combined_data_10.csv'
Combined data for 11 files saved to 'ChaoShenCSV\16\combined_data_11.csv'
Combined data for 12 files saved to 'ChaoShenCSV\16\combined_data_12.csv'
Combined data for 13 files saved to 'ChaoShenCSV\16\combined_data_13.csv'
Combined data for 14 files saved to 'ChaoShenCSV\16\combined_data_14.csv'
Combined data for 15 files saved to 'ChaoShenCSV\16\combined_data_15.csv'
Combined data for 16 files saved to 'ChaoShenCSV\16\combined_data_16.csv'
Combined data for 17 files saved to 'ChaoShenCSV\16\combined_data_17.csv'
Combined data for 18 files saved to 'ChaoShenCSV\16\combined_data_18.csv'
Combined data for 19 files saved to 'ChaoShenCSV\16\combined_data_19.csv'
Combined data for 2 files saved to 'ChaoShenCSV\16\combined_data_2.csv'
Combined data for 20 files saved to 'ChaoShenCSV\16\combined_data_20.csv'
Combined data for 21 files saved to 'ChaoShenCSV\16\combined_data_21.csv'
Combined data for 22 files saved to 'ChaoShenCSV\16\combined_data_22.csv'
Combined data for 23 files saved to 'ChaoShenCSV\16\combined_data_23.csv'
Combined data for 24 files saved to 'ChaoShenCSV\16\combined_data_24.csv'
Combined data for 3 files saved to 'ChaoShenCSV\16\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\16\combined_data_4.csv'
Combined data for 5 files saved to 'ChaoShenCSV\16\combined_data_5.csv'
Combined data for 6 files saved to 'ChaoShenCSV\16\combined_data_6.csv'
Combined data for 7 files saved to 'ChaoShenCSV\16\combined_data_7.csv'
Combined data for 8 files saved to 'ChaoShenCSV\16\combined_data_8.csv'
Combined data for 9 files saved to 'ChaoShenCSV\16\combined_data_9.csv'
1_1.ef
1_2.ef
1_3.ef
1_4.ef
2_1.ef
2_2.ef
2_3.ef
2_4.ef
2_5.ef
2_6.ef
2_7.ef
2_8.ef
3_1.ef
3_2.ef
3_3.ef
3_4.ef
3_5.ef
3_6.ef
3_7.ef
3_8.ef
3_9.ef
Combined data for 1 files saved to 'ChaoShenCSV\17\combined_data_1.csv'
Combined data for 2 files saved to 'ChaoShenCSV\17\combined_data_2.csv'
Combined data for 3 files saved to 'ChaoShenCSV\17\combined_data_3.csv'
1.ef
2.ef
3.ef
4.ef
5.ef
6.ef
7.ef
Combined data for 1 files saved to 'ChaoShenCSV\18\combined_data_1.csv'
Combined data for 2 files saved to 'ChaoShenCSV\18\combined_data_2.csv'
Combined data for 3 files saved to 'ChaoShenCSV\18\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\18\combined_data_4.csv'
Combined data for 5 files saved to 'ChaoShenCSV\18\combined_data_5.csv'
Combined data for 6 files saved to 'ChaoShenCSV\18\combined_data_6.csv'
Combined data for 7 files saved to 'ChaoShenCSV\18\combined_data_7.csv'
1.ef
10.ef
2.ef
3.ef
4.ef
5.ef
6.ef
7.ef
8.ef
9.ef
Combined data for 1 files saved to 'ChaoShenCSV\19\combined_data_1.csv'
Combined data for 10 files saved to 'ChaoShenCSV\19\combined_data_10.csv'
Combined data for 2 files saved to 'ChaoShenCSV\19\combined_data_2.csv'
Combined data for 3 files saved to 'ChaoShenCSV\19\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\19\combined_data_4.csv'
Combined data for 5 files saved to 'ChaoShenCSV\19\combined_data_5.csv'
Combined data for 6 files saved to 'ChaoShenCSV\19\combined_data_6.csv'
Combined data for 7 files saved to 'ChaoShenCSV\19\combined_data_7.csv'
Combined data for 8 files saved to 'ChaoShenCSV\19\combined_data_8.csv'
Combined data for 9 files saved to 'ChaoShenCSV\19\combined_data_9.csv'
1_1.ef
1_10.ef
1_11.ef
1_12.ef
1_13.ef
1_14.ef
1_15.ef
1_16.ef
1_17.ef
1_18.ef
1_19.ef
1_2.ef
1_20.ef
1_21.ef
1_22.ef
1_23.ef
1_24.ef
1_25.ef
1_26.ef
1_27.ef
1_28.ef
1_3.ef
1_4.ef
1_5.ef
1_6.ef
1_7.ef
1_8.ef
1_9.ef
2_1.ef
2_10.ef
2_11.ef
2_12.ef
2_13.ef
2_14.ef
2_15.ef
2_16.ef
2_17.ef
2_2.ef
2_3.ef
2_4.ef
2_5.ef
2_6.ef
2_7.ef
2_8.ef
2_9.ef
3_1.ef
3_10.ef
3_11.ef
3_12.ef
3_13.ef
3_14.ef
3_15.ef
3_16.ef
3_17.ef
3_18.ef
3_19.ef
3_2.ef
3_20.ef
3_21.ef
3_22.ef
3_23.ef
3_3.ef
3_4.ef
3_5.ef
3_6.ef
3_7.ef
3_8.ef
3_9.ef
4_1.ef
Combined data for 1 files saved to 'ChaoShenCSV\2\combined_data_1.csv'
Combined data for 2 files saved to 'ChaoShenCSV\2\combined_data_2.csv'
Combined data for 3 files saved to 'ChaoShenCSV\2\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\2\combined_data_4.csv'
1.ef
10.ef
11.ef
12.ef
13.ef
14.ef
15.ef
16.ef
17.ef
18.ef
2.ef
3.ef
4.ef
5.ef
6.ef
7.ef
8.ef
9.ef
Combined data for 1 files saved to 'ChaoShenCSV\20\combined_data_1.csv'
Combined data for 10 files saved to 'ChaoShenCSV\20\combined_data_10.csv'
Combined data for 11 files saved to 'ChaoShenCSV\20\combined_data_11.csv'
Combined data for 12 files saved to 'ChaoShenCSV\20\combined_data_12.csv'
Combined data for 13 files saved to 'ChaoShenCSV\20\combined_data_13.csv'
Combined data for 14 files saved to 'ChaoShenCSV\20\combined_data_14.csv'
Combined data for 15 files saved to 'ChaoShenCSV\20\combined_data_15.csv'
Combined data for 16 files saved to 'ChaoShenCSV\20\combined_data_16.csv'
Combined data for 17 files saved to 'ChaoShenCSV\20\combined_data_17.csv'
Combined data for 18 files saved to 'ChaoShenCSV\20\combined_data_18.csv'
Combined data for 2 files saved to 'ChaoShenCSV\20\combined_data_2.csv'
Combined data for 3 files saved to 'ChaoShenCSV\20\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\20\combined_data_4.csv'
Combined data for 5 files saved to 'ChaoShenCSV\20\combined_data_5.csv'
Combined data for 6 files saved to 'ChaoShenCSV\20\combined_data_6.csv'
Combined data for 7 files saved to 'ChaoShenCSV\20\combined_data_7.csv'
Combined data for 8 files saved to 'ChaoShenCSV\20\combined_data_8.csv'
Combined data for 9 files saved to 'ChaoShenCSV\20\combined_data_9.csv'
1.ef
10.ef
11.ef
12.ef
2.ef
3.ef
4.ef
5.ef
6.ef
7.ef
8.ef
9.ef
Combined data for 1 files saved to 'ChaoShenCSV\21\combined_data_1.csv'
Combined data for 10 files saved to 'ChaoShenCSV\21\combined_data_10.csv'
Combined data for 11 files saved to 'ChaoShenCSV\21\combined_data_11.csv'
Combined data for 12 files saved to 'ChaoShenCSV\21\combined_data_12.csv'
Combined data for 2 files saved to 'ChaoShenCSV\21\combined_data_2.csv'
Combined data for 3 files saved to 'ChaoShenCSV\21\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\21\combined_data_4.csv'
Combined data for 5 files saved to 'ChaoShenCSV\21\combined_data_5.csv'
Combined data for 6 files saved to 'ChaoShenCSV\21\combined_data_6.csv'
Combined data for 7 files saved to 'ChaoShenCSV\21\combined_data_7.csv'
Combined data for 8 files saved to 'ChaoShenCSV\21\combined_data_8.csv'
Combined data for 9 files saved to 'ChaoShenCSV\21\combined_data_9.csv'
19.ef
20.ef
21.ef
22.ef
23.ef
24.ef
25.ef
26.ef
27.ef
28.ef
29.ef
30.ef
31.ef
32.ef
33.ef
34.ef
35.ef
36.ef
37.ef
38.ef
39.ef
Combined data for 19 files saved to 'ChaoShenCSV\22\combined_data_19.csv'
Combined data for 20 files saved to 'ChaoShenCSV\22\combined_data_20.csv'
Combined data for 21 files saved to 'ChaoShenCSV\22\combined_data_21.csv'
Combined data for 22 files saved to 'ChaoShenCSV\22\combined_data_22.csv'
Combined data for 23 files saved to 'ChaoShenCSV\22\combined_data_23.csv'
Combined data for 24 files saved to 'ChaoShenCSV\22\combined_data_24.csv'
Combined data for 25 files saved to 'ChaoShenCSV\22\combined_data_25.csv'
Combined data for 26 files saved to 'ChaoShenCSV\22\combined_data_26.csv'
Combined data for 27 files saved to 'ChaoShenCSV\22\combined_data_27.csv'
Combined data for 28 files saved to 'ChaoShenCSV\22\combined_data_28.csv'
Combined data for 29 files saved to 'ChaoShenCSV\22\combined_data_29.csv'
Combined data for 30 files saved to 'ChaoShenCSV\22\combined_data_30.csv'
Combined data for 31 files saved to 'ChaoShenCSV\22\combined_data_31.csv'
Combined data for 32 files saved to 'ChaoShenCSV\22\combined_data_32.csv'
Combined data for 33 files saved to 'ChaoShenCSV\22\combined_data_33.csv'
Combined data for 34 files saved to 'ChaoShenCSV\22\combined_data_34.csv'
Combined data for 35 files saved to 'ChaoShenCSV\22\combined_data_35.csv'
Combined data for 36 files saved to 'ChaoShenCSV\22\combined_data_36.csv'
Combined data for 37 files saved to 'ChaoShenCSV\22\combined_data_37.csv'
Combined data for 38 files saved to 'ChaoShenCSV\22\combined_data_38.csv'
Combined data for 39 files saved to 'ChaoShenCSV\22\combined_data_39.csv'
2_1.ef
2_2.ef
2_3.ef
2_4.ef
2_5.ef
2_6.ef
39_1.ef
39_2.ef
39_3.ef
39_4.ef
7_1.ef
7_2.ef
7_3.ef
7_4.ef
7_5.ef
8_1.ef
8_10.ef
8_11.ef
8_2.ef
8_3.ef
8_4.ef
8_5.ef
8_6.ef
8_7.ef
8_8.ef
8_9.ef
Combined data for 2 files saved to 'ChaoShenCSV\23\combined_data_2.csv'
Combined data for 39 files saved to 'ChaoShenCSV\23\combined_data_39.csv'
Combined data for 7 files saved to 'ChaoShenCSV\23\combined_data_7.csv'
Combined data for 8 files saved to 'ChaoShenCSV\23\combined_data_8.csv'
1.ef
2.ef
3.ef
3_1.ef
4_1.ef
4_2.ef
4_3.ef
5.ef
5_1.ef
6_1.ef
6_2.ef
6_3.ef
6_4.ef
7.ef
7_1.ef
Combined data for 1 files saved to 'ChaoShenCSV\24\combined_data_1.csv'
Combined data for 2 files saved to 'ChaoShenCSV\24\combined_data_2.csv'
Combined data for 3 files saved to 'ChaoShenCSV\24\combined_data_3.csv'
Combined data for 4 files saved to 'ChaoShenCSV\24\combined_data_4.csv'
Combined data for 5 files saved to 'ChaoShenCSV\24\combined_data_5.csv'
Combined data for 6 files saved to 'ChaoShenCSV\24\combined_data_6.csv'
Combined data for 7 files saved to 'ChaoShenCSV\24\combined_data_7.csv'
1_1.ef
1_10.ef
1_2.ef
1_3.ef
1_4.ef
1_5.ef
1_6.ef
1_7.ef
1_8.ef
1_9.ef
2_1.ef
Combined data for 1 files saved to 'ChaoShenCSV\25\combined_data_1.csv'
Combined data for 2 files saved to 'ChaoShenCSV\25\combined_data_2.csv'
1_1.ef
1_2.ef
2_1.ef
2_10.ef
2_11.ef
2_12.ef
2_13.ef
2_2.ef
2_3.ef
2_4.ef
2_5.ef
2_6.ef
2_7.ef
2_8.ef
2_9.ef
Combined data for 1 files saved to 'ChaoShenCSV\26\combined_data_1.csv'
Combined data for 2 files saved to 'ChaoShenCSV\26\combined_data_2.csv'
6_1.ef
6_10.ef
6_11.ef
6_2.ef
6_3.ef
6_4.ef
6_5.ef
6_6.ef
6_7.ef
6_8.ef
6_9.ef
7_1.ef
7_2.ef
7_3.ef
8_1.ef
8_2.ef
8_3.ef
8_4.ef
8_5.ef
8_6.ef
9_1.ef
9_2.ef
9_3.ef

In [115]:
df = pd.read_csv('ChaoShenCSV\\1\\combined_data_1.csv')

In [116]:
df

           x    y  ncode                     event  TimeStamp  ProcessNo
0        399  363    512  MouseEvent(WM_MOUSEMOVE)    2889111          0
1        401  364    512  MouseEvent(WM_MOUSEMOVE)    2889120          0
2        401  366    512  MouseEvent(WM_MOUSEMOVE)    2889130          0
3        405  369    512  MouseEvent(WM_MOUSEMOVE)    2889140          0
4        410  372    512  MouseEvent(WM_MOUSEMOVE)    2889151          0
...      ...  ...    ...                       ...        ...        ...
719995  1245  718    512  MouseEvent(WM_MOUSEMOVE)  134920256          3
719996  1245  718    512  MouseEvent(WM_MOUSEMOVE)  134920257          3
719997  1245  718    512  MouseEvent(WM_MOUSEMOVE)  134920349          3
719998  1245  718    512  MouseEvent(WM_MOUSEMOVE)  134920349          3
719999  1245  718    512  MouseEvent(WM_MOUSEMOVE)  134920461          3

[720000 rows x 6 columns]

In [117]:
event_counts = df["event"].value_counts()
print(event_counts)

MouseEvent(WM_MOUSEMOVE)    654812
Unknown                      53761
MouseEvent(WM_LBUTTONUP)      5903
Click()                       5054
DblClick()                     229
RightClick()                   121
MouseEvent(WM_RBUTTONUP)       118
RightDblClick()                  2
Name: event, dtype: int64

In [6]:
df = pd.read_csv('chaoshen_dataset_users[1, 2, 4]_limit1000000_labelsFalse.csv')

In [8]:
event_counts = df["type_of_action"].value_counts()
print(event_counts)

3    32813
1     6573
Name: type_of_action, dtype: int64

In [11]:
df = pd.read_csv('chaoshen_dataset_users[1, 2, 4]_limit1000000_labelsFalse.csv')
event_counts = df["type_of_action"].value_counts()
print(event_counts)

1    64163
4    41975
3    27662
Name: type_of_action, dtype: int64